version: '2'
services:
  taigadata:
    image: tianon/true
    volumes:
      - './volumes/data:/var/lib/postgresql/data'
      - './volumes/media:/usr/local/taiga/media'
      - './volumes/static:/usr/local/taiga/static'
      - './volumes/logs:/usr/local/taiga/logs'
    network_mode: bridge

  taigadb:
    image: postgres
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes_from:
      - taigadata
    network_mode: bridge

  taigaback:
    build: ./taiga-back
    links:
      - taigadb:postgres
    volumes_from:
      - taigadata
    environment:
      - SECRET_KEY=$SECRET_KEY

      - PUBLIC_REGISTER_ENABLED=$PUBLIC_REGISTER_ENABLED
      - FEEDBACK_ENABLED=$FEEDBACK_ENABLED
      - FEEDBACK_EMAIL=$FEEDBACK_EMAIL
      - STATS_ENABLED=$STATS_ENABLED

      - FRONT_SITEMAP_ENABLED=$FRONT_SITEMAP_ENABLED

      - SAMPLE_DATA=$SAMPLE_DATA

      - DEBUG_ENTRYPOINT=$DEBUG_ENTRYPOINT
      - DEBUG=$DEBUG
      - TEMPLATE_DEBUG=$TEMPLATE_DEBUG
      - EMAIL_USE_TLS=$EMAIL_USE_TLS
      - EMAIL_HOST=$EMAIL_HOST
      - EMAIL_PORT=$EMAIL_PORT
      - EMAIL_HOST_USER=$EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
      - DEFAULT_FROM_EMAIL=$DEFAULT_FROM_EMAIL
    network_mode: bridge

  taigafront:
    image: beevelop/taiga-front
    links:
      - taigaback
    volumes_from:
      - taigadata
    environment: 
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_HOST=$LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
    network_mode: bridge
